FROM golang:1.21.0@sha256:ec457a2fcd235259273428a24e09900c496d0c52207266f96a330062a01e3622
COPY build/ssh.conf /etc/ssh/ssh_config.d/

RUN go install github.com/google/go-licenses@latest
# Ruby used for polyglot hook integration tests
RUN apt update && apt install -y ruby
